// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMANGgZXJYvu8MTtTMAdwgKSKWdZK5IRM',
    appId: '1:862786682401:web:1298d7c135aef445cead60',
    messagingSenderId: '862786682401',
    projectId: 'auth-c672c',
    authDomain: 'auth-c672c.firebaseapp.com',
    storageBucket: 'auth-c672c.appspot.com',
    measurementId: 'G-4PV2D1DNZ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1BvVwtQS8RYRllNKG5aiopytb34HskEA',
    appId: '1:862786682401:android:06404ff1befed922cead60',
    messagingSenderId: '862786682401',
    projectId: 'auth-c672c',
    storageBucket: 'auth-c672c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxbj5nAXK3io5bBz1TWTDoIvX3hqmnEfs',
    appId: '1:862786682401:ios:b40b7b62f546083bcead60',
    messagingSenderId: '862786682401',
    projectId: 'auth-c672c',
    storageBucket: 'auth-c672c.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxbj5nAXK3io5bBz1TWTDoIvX3hqmnEfs',
    appId: '1:862786682401:ios:be0a72d38e2cdfbacead60',
    messagingSenderId: '862786682401',
    projectId: 'auth-c672c',
    storageBucket: 'auth-c672c.appspot.com',
    iosBundleId: 'com.example.app.RunnerTests',
  );
}
